- hosts: all
  become: true

  roles:
    - clone-devstack-gate-to-workspace
    - create-devstack-local-conf
    - install-devstack

- hosts: all
  tasks:
    - name: Prepare flavor for tests
      shell:
        cmd: |
          source openrc admin admin
          set -eux -o pipefail

          openstack flavor create test-flavor --ram 512 --disk 5 --vcpu 1 --public
        executable: /bin/bash
        chdir: /opt/stack/new/devstack

    - name: Run tests
      shell:
        cmd: |
          source /opt/stack/new/devstack/openrc demo demo
          set -eux -o pipefail

          for i in $HOME/.ssh/id_rsa.pub $HOME/.ssh/id_dsa.pub; do
            if [[ -r $i ]]; then
              KEYPAIR_FILE=$i
              break
            fi
          done

          export RUST_OPENSTACK_FLAVOR=test-flavor
          export RUST_OPENSTACK_NETWORK=private
          export RUST_OPENSTACK_IMAGE=$(openstack image list -f value -c ID -c Name \
            | awk '/cirros/ { print $1; exit 0; }')
          export RUST_OPENSTACK_KEYPAIR=$KEYPAIR_FILE

          if [ -z $RUST_OPENSTACK_IMAGE ]; then
            echo FATAL: cirros image not found
            openstack image list
            exit 1
          fi

          export RUST_BACKTRACE=1
          export RUST_LOG=openstack

          cargo build --release --all-features
          cargo test -- --test-threads=1
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
