[package]

name = "openstack"
description = "OpenStack Client"
version = "0.0.1"
authors = ["Dmitry Tantsur <divius.inside@gmail.com>"]
homepage = "https://github.com/dtantsur/rust-openstack"
readme = "README.md"
license = "Apache-2.0"

[dependencies]

log = "^0.3"

[lib]

name = "openstack"
path = "src/lib.rs"
