[package]

name = "openstack"
description = "OpenStack SDK for Rust"
version = "0.0.15"
authors = ["Dmitry Tantsur <divius.inside@gmail.com>"]
homepage = "https://dtantsur.github.io/rust-openstack/openstack/"
repository = "https://github.com/dtantsur/rust-openstack"
documentation = "https://dtantsur.github.io/rust-openstack/openstack/"
readme = "README.md"
license = "Apache-2.0"
keywords = ["api", "cloud", "openstack"]
categories = ["api-bindings"]

[features]

default = ["tls", "compute"]
tls = ["hyper-rustls"]
compute = []

[dependencies]

chrono = { version = "^0.4", features = ["serde"] }
hyper = "^0.10"
log = "^0.3"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

hyper-rustls = { version = "^0.6", optional = true }

[dev-dependencies]
env_logger = "^0.4"
yup-hyper-mock = "^2.0"

[lib]

name = "openstack"
path = "src/lib.rs"

[badges]
travis-ci = { repository = "dtantsur/rust-openstack" }
