- project:
    check:
      jobs:
        - rust-openstack-acceptance
        - rust-openstack-acceptance-train
        - rust-openstack-acceptance-stein
        - rust-openstack-acceptance-rocky
        - rust-openstack-acceptance-queens
        - rust-openstack-acceptance-nightly
